#server:
  #port: ${PORT:8080}

#spring:
  #datasource:
    #url: jdbc:postgresql://localhost:5432/cities

    #username: postgres

    #password: GilGPACD12!

server:
  port: 8080

spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cities
    username: postgres
    password: GilGPACD12!
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update